services:
  ldap:
    container_name: ldap
    image: dcm4che/slapd-dcm4chee:2.4.44-12.0
    restart: unless-stopped
    ports:
      - "${LDAP_PORT}:389"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/placax-reports/ldap:/var/lib/ldap
      - /var/local/placax-reports/slapd.d:/etc/ldap/slapd.d
  db:
    container_name: db
    image: dcm4che/postgres-dcm4chee:10.0-12
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: pacsdb
      POSTGRES_USER: pacs
      POSTGRES_PASSWORD: ${DB_PW}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/placax-reports/db:/var/lib/postgresql/data
  arc:
    container_name: arc
    image: dcm4che/dcm4chee-arc-psql:5.12.0
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "${ARC_PORT8080}:8080"
      - "${ARC_PORT8443}:8443"
      - "${ARC_PORT9990}:9990"
      - "${ARC_PORT11112}:11112"
      - "${ARC_PORT2575}:2575"
    environment:
      POSTGRES_DB: pacsdb
      POSTGRES_USER: pacs
      POSTGRES_PASSWORD: ${DB_PW}
      WILDFLY_WAIT_FOR: ldap:389 db:5432
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/placax-reports/wildfly:/opt/wildfly/standalone
  oviyam:
    container_name: oviyam
    image:  postar/oviyam:1.0.2
    restart: unless-stopped
    depends_on:
      - arc
    ports:
      - "${OVIYAM_8080}:8080"
      - "${OVIYAM_1025}:1025"
    volumes:
      - /var/local/placax-reports/oviyam:/usr/local/tomcat/work
  reportsdb:
    container_name: reportsdb
    image: mysql:8.0.23
    restart: unless-stopped
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PW}
    volumes:
     - /var/local/placax-reports/reportsdb:/var/lib/mysql
    networks:
      default:
        ipv4_address: 172.20.0.44
  plaxreports:
    container_name: plaxreports
    image:  alejovac/dpacsreports:1.0.1
    depends_on:
      - reportsdb
      - arc
    restart: unless-stopped
    ports:
      - "${REPORTSBACK_80}:80"
      - "${REPORTSBACK_443}:443"
    environment:
        ASPNETCORE_ENVIRONMENT: Development
        OPACSVIEWERURL: ${OPACSVIEWERURL}
        DBSERVER: reportsdb
        DBPORT: 3306
        DBPASS: ${DB_PW}
    networks:
      default:
        ipv4_address: 172.20.0.33
  reportsworker:
    container_name: reportsworker
    image: alejovac/dpacsworker:1.0.3
    restart: unless-stopped
    depends_on:
      - reportsdb
    environment:
        DBSERVER: reportsdb #172.20.0.44
        DBPORT: 3306
        DCM4CHEESERVER: db #192.168.1.81
        DCM4CHEEPORT: 5432
        DCM4CHEEPASS: ${DB_PW}
        DBPASS: ${DB_PW}
  reportsweb:
    container_name: reportsweb
    image: alejovac/opacsreportsweb:v1.0.26
    restart: unless-stopped
    ports:
      - "${REPORTS_PORT80}:80"
      - "${REPORTS_PORT443}:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    restart: unless-stopped
    container_name: tunnel
networks:
  default:
      name: dcm4chee_default
      driver: bridge
      ipam:
        config:
          - subnet: 172.20.0.0/24