services:
  apilicense:
    container_name: apilicense
    image: alejovac/mesyapilicense:0.1.2
    restart: unless-stopped
    user: root
    ports:
      - "80:8080"
      - "443:8081"
    volumes:
     - /var/local/mesy-lico/api/clients:/app/data